all:
  hosts:
    inno:
      ansible_host: [ADDRESS]
      ansible_connection: ssh
      ansible_user: app
      ansible_ssh_private_key_file: ./id_ecdsa
      ansible_ssh_common_args: '-o "StrictHostKeyChecking no"'
      ansible_python_interpreter: auto
      config_domain: [DOMAIN]
      config_acme_email: [ACME_EMAIL]